spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true
      
# if we just add spring starter dependency it will provide automatic security by login page
#the credentials will be user and password is provided in the console logs
#how ever we can customize the credentials by below props
  security:
      user:
        name: mahendra
        password: 12345


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TestBoot?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
management:
   security:
      enabled: false
#   endpoints:
#           web:
#             exposure:
#                include: health,info,beans,env
